<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED value CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED value CDATA #IMPLIED><!ATTLIST buffer-attribute name CDATA #REQUIRED value CDATA #IMPLIED>]><context name="network" description="10.72.162.61 Linux analog 5.4.0-00534-g01f158943992 #10 SMP Thu Dec 9 14:15:06 EET 2021 aarch64" ><context-attribute name="hdl_system_id" value="[adv7511] on [zed] git &lt;2e4ac278eb09c13471e381459b0da790ebad8373&gt; clean [2019-12-05 01:36:48] UTC" /><context-attribute name="local,kernel" value="5.4.0-00534-g01f158943992" /><context-attribute name="uri" value="ip:10.72.162.61" /><context-attribute name="ip,ip-addr" value="10.72.162.61" /><device id="iio:device0" name="ams" ><channel id="voltage6" name="vccpsintfpddr" type="input" ><attribute name="raw" filename="in_voltage6_vccpsintfpddr_raw" value="18393" /><attribute name="scale" filename="in_voltage6_vccpsintfpddr_scale" value="0.045776367" /></channel><channel id="voltage14" name="vccpsio2" type="input" ><attribute name="raw" filename="in_voltage14_vccpsio2_raw" value="19460" /><attribute name="scale" filename="in_voltage14_vccpsio2_scale" value="0.091552734" /></channel><channel id="voltage16" name="psmgtravtt" type="input" ><attribute name="raw" filename="in_voltage16_psmgtravtt_raw" value="39578" /><attribute name="scale" filename="in_voltage16_psmgtravtt_scale" value="0.045776367" /></channel><channel id="voltage23" name="vccplintlp" type="input" ><attribute name="raw" filename="in_voltage23_vccplintlp_raw" value="18522" /><attribute name="scale" filename="in_voltage23_vccplintlp_scale" value="0.045776367" /></channel><channel id="voltage0" name="vcc_pspll0" type="input" ><attribute name="raw" filename="in_voltage0_vcc_pspll0_raw" value="26125" /><attribute name="scale" filename="in_voltage0_vcc_pspll0_scale" value="0.045776367" /></channel><channel id="voltage22" name="vccbram" type="input" ><attribute name="raw" filename="in_voltage22_vccbram_raw" value="18453" /><attribute name="scale" filename="in_voltage22_vccbram_scale" value="0.045776367" /></channel><channel id="voltage26" name="vccams" type="input" ><attribute name="raw" filename="in_voltage26_vccams_raw" value="39151" /><attribute name="scale" filename="in_voltage26_vccams_scale" value="0.015258789" /></channel><channel id="voltage8" name="vccpsintfp" type="input" ><attribute name="raw" filename="in_voltage8_vccpsintfp_raw" value="18440" /><attribute name="scale" filename="in_voltage8_vccpsintfp_scale" value="0.045776367" /></channel><channel id="temp1" name="remote_temp" type="input" ><attribute name="offset" filename="in_temp1_remote_temp_offset" value="-36058" /><attribute name="raw" filename="in_temp1_remote_temp_raw" value="40650" /><attribute name="scale" filename="in_temp1_remote_temp_scale" value="7.771514892" /></channel><channel id="voltage9" name="vccpsaux" type="input" ><attribute name="raw" filename="in_voltage9_vccpsaux_raw" value="39515" /><attribute name="scale" filename="in_voltage9_vccpsaux_scale" value="0.045776367" /></channel><channel id="voltage25" name="vccplaux" type="input" ><attribute name="raw" filename="in_voltage25_vccplaux_raw" value="39602" /><attribute name="scale" filename="in_voltage25_vccplaux_scale" value="0.045776367" /></channel><channel id="voltage18" name="vccint" type="input" ><attribute name="raw" filename="in_voltage18_vccint_raw" value="18479" /><attribute name="scale" filename="in_voltage18_vccint_scale" value="0.045776367" /></channel><channel id="voltage15" name="psmgtravcc" type="input" ><attribute name="raw" filename="in_voltage15_psmgtravcc_raw" value="18506" /><attribute name="scale" filename="in_voltage15_psmgtravcc_scale" value="0.045776367" /></channel><channel id="temp0" name="ps_temp" type="input" ><attribute name="offset" filename="in_temp0_ps_temp_offset" value="-36058" /><attribute name="raw" filename="in_temp0_ps_temp_raw" value="40694" /><attribute name="scale" filename="in_temp0_ps_temp_scale" value="7.771514892" /></channel><channel id="voltage2" name="vccint" type="input" ><attribute name="raw" filename="in_voltage2_vccint_raw" value="18462" /><attribute name="scale" filename="in_voltage2_vccint_scale" value="0.045776367" /></channel><channel id="voltage5" name="vcc_psddrpll" type="input" ><attribute name="raw" filename="in_voltage5_vcc_psddrpll_raw" value="39612" /><attribute name="scale" filename="in_voltage5_vcc_psddrpll_scale" value="0.045776367" /></channel><channel id="voltage21" name="vccvrefn" type="input" ><attribute name="raw" filename="in_voltage21_vccvrefn_raw" value="0" /><attribute name="scale" filename="in_voltage21_vccvrefn_scale" value="0.015258789" /></channel><channel id="voltage7" name="vccpsintlp" type="input" ><attribute name="raw" filename="in_voltage7_vccpsintlp_raw" value="18444" /><attribute name="scale" filename="in_voltage7_vccpsintlp_scale" value="0.045776367" /></channel><channel id="voltage11" name="vccpsio3" type="input" ><attribute name="raw" filename="in_voltage11_vccpsio3_raw" value="19606" /><attribute name="scale" filename="in_voltage11_vccpsio3_scale" value="0.091552734" /></channel><channel id="temp2" name="pl_temp" type="input" ><attribute name="offset" filename="in_temp2_pl_temp_offset" value="-36058" /><attribute name="raw" filename="in_temp2_pl_temp_raw" value="40688" /><attribute name="scale" filename="in_temp2_pl_temp_scale" value="7.771514892" /></channel><channel id="voltage13" name="vccpsio1" type="input" ><attribute name="raw" filename="in_voltage13_vccpsio1_raw" value="19473" /><attribute name="scale" filename="in_voltage13_vccpsio1_scale" value="0.091552734" /></channel><channel id="voltage3" name="vccbram" type="input" ><attribute name="raw" filename="in_voltage3_vccbram_raw" value="18395" /><attribute name="scale" filename="in_voltage3_vccbram_scale" value="0.045776367" /></channel><channel id="voltage4" name="vccaux" type="input" ><attribute name="raw" filename="in_voltage4_vccaux_raw" value="39138" /><attribute name="scale" filename="in_voltage4_vccaux_scale" value="0.045776367" /></channel><channel id="voltage12" name="vccpsio0" type="input" ><attribute name="raw" filename="in_voltage12_vccpsio0_raw" value="19466" /><attribute name="scale" filename="in_voltage12_vccpsio0_scale" value="0.091552734" /></channel><channel id="voltage10" name="vccpsddr" type="input" ><attribute name="raw" filename="in_voltage10_vccpsddr_raw" value="25905" /><attribute name="scale" filename="in_voltage10_vccpsddr_scale" value="0.045776367" /></channel><channel id="voltage24" name="vccplintfp" type="input" ><attribute name="raw" filename="in_voltage24_vccplintfp_raw" value="18434" /><attribute name="scale" filename="in_voltage24_vccplintfp_scale" value="0.045776367" /></channel><channel id="voltage1" name="vcc_psbatt" type="input" ><attribute name="raw" filename="in_voltage1_vcc_psbatt_raw" value="37101" /><attribute name="scale" filename="in_voltage1_vcc_psbatt_scale" value="0.045776367" /></channel><channel id="voltage19" name="vccaux" type="input" ><attribute name="raw" filename="in_voltage19_vccaux_raw" value="39234" /><attribute name="scale" filename="in_voltage19_vccaux_scale" value="0.045776367" /></channel><channel id="voltage17" name="vccams" type="input" ><attribute name="raw" filename="in_voltage17_vccams_raw" value="39477" /><attribute name="scale" filename="in_voltage17_vccams_scale" value="0.015258789" /></channel><channel id="voltage20" name="vccvrefp" type="input" ><attribute name="raw" filename="in_voltage20_vccvrefp_raw" value="27314" /><attribute name="scale" filename="in_voltage20_vccvrefp_scale" value="0.015258789" /></channel><attribute name="sampling_frequency" value="ERROR" /></device><device id="iio:device1" name="hmc7044" ><channel id="altvoltage10" name="CORE_CLK_RX_ALT" type="output" ><attribute name="frequency" filename="out_altvoltage10_CORE_CLK_RX_ALT_frequency" value="250000000" /><attribute name="phase" filename="out_altvoltage10_CORE_CLK_RX_ALT_phase" value="0.000000" /></channel><channel id="altvoltage0" name="CORE_CLK_RX" type="output" ><attribute name="frequency" filename="out_altvoltage0_CORE_CLK_RX_frequency" value="250000000" /><attribute name="phase" filename="out_altvoltage0_CORE_CLK_RX_phase" value="0.000000" /></channel><channel id="altvoltage3" name="DEV_SYSREF" type="output" ><attribute name="frequency" filename="out_altvoltage3_DEV_SYSREF_frequency" value="1953125" /><attribute name="phase" filename="out_altvoltage3_DEV_SYSREF_phase" value="0.000000" /></channel><channel id="altvoltage13" name="FPGA_SYSREF" type="output" ><attribute name="frequency" filename="out_altvoltage13_FPGA_SYSREF_frequency" value="1953125" /><attribute name="phase" filename="out_altvoltage13_FPGA_SYSREF_phase" value="0.000000" /></channel><channel id="altvoltage6" name="CORE_CLK_TX" type="output" ><attribute name="frequency" filename="out_altvoltage6_CORE_CLK_TX_frequency" value="250000000" /><attribute name="phase" filename="out_altvoltage6_CORE_CLK_TX_phase" value="0.000000" /></channel><channel id="altvoltage2" name="DEV_REFCLK" type="output" ><attribute name="frequency" filename="out_altvoltage2_DEV_REFCLK_frequency" value="250000000" /><attribute name="phase" filename="out_altvoltage2_DEV_REFCLK_phase" value="0.000000" /></channel><channel id="altvoltage8" name="FPGA_REFCLK1" type="output" ><attribute name="frequency" filename="out_altvoltage8_FPGA_REFCLK1_frequency" value="500000000" /><attribute name="phase" filename="out_altvoltage8_FPGA_REFCLK1_phase" value="0.000000" /></channel><channel id="altvoltage12" name="FPGA_REFCLK2" type="output" ><attribute name="frequency" filename="out_altvoltage12_FPGA_REFCLK2_frequency" value="500000000" /><attribute name="phase" filename="out_altvoltage12_FPGA_REFCLK2_phase" value="0.000000" /></channel><attribute name="mute_request" value="0" /><attribute name="reseed_request" value="0" /><attribute name="reset_dividers_request" value="0" /><attribute name="sleep_request" value="0" /><attribute name="sync_pin_mode" value="sync" /><attribute name="sync_pin_mode_available" value="disable sync sysref sync_else_sysref" /><attribute name="sysref_request" value="0" /><debug-attribute name="status" value="ERROR" /><debug-attribute name="direct_reg_access" value="0x0" /></device><device id="iio:device10" name="one-bit-adc-dac" ><channel id="voltage1" type="output" ><attribute name="label" filename="out_voltage1_label" value="UPDATE" /><attribute name="raw" filename="out_voltage1_raw" value="0" /></channel><channel id="voltage0" type="output" ><attribute name="label" filename="out_voltage0_label" value="MUTE" /><attribute name="raw" filename="out_voltage0_raw" value="0" /></channel><channel id="voltage2" type="output" ><attribute name="label" filename="out_voltage2_label" value="RESET" /><attribute name="raw" filename="out_voltage2_raw" value="0" /></channel></device><device id="iio:device11" name="adar3002_csb_0_0" ><channel id="phase0" type="output" ><scan-element index="0" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase0_label" value="BEAM0_H_EL0_DELAY" /><attribute name="raw" filename="out_phase0_raw" value="3" /><attribute name="scale" filename="out_phase0_scale" value="5.714285714" /></channel><channel id="power0" type="output" ><scan-element index="1" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power0_label" value="BEAM0_H_EL0_ATTENUATION" /><attribute name="raw" filename="out_power0_raw" value="0" /><attribute name="scale" filename="out_power0_scale" value="0.492063492" /></channel><channel id="phase1" type="output" ><scan-element index="2" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase1_label" value="BEAM0_H_EL1_DELAY" /><attribute name="raw" filename="out_phase1_raw" value="3" /><attribute name="scale" filename="out_phase1_scale" value="5.714285714" /></channel><channel id="power1" type="output" ><scan-element index="3" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power1_label" value="BEAM0_H_EL1_ATTENUATION" /><attribute name="raw" filename="out_power1_raw" value="0" /><attribute name="scale" filename="out_power1_scale" value="0.492063492" /></channel><channel id="phase2" type="output" ><scan-element index="4" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase2_label" value="BEAM0_H_EL2_DELAY" /><attribute name="raw" filename="out_phase2_raw" value="2" /><attribute name="scale" filename="out_phase2_scale" value="5.714285714" /></channel><channel id="power2" type="output" ><scan-element index="5" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power2_label" value="BEAM0_H_EL2_ATTENUATION" /><attribute name="raw" filename="out_power2_raw" value="0" /><attribute name="scale" filename="out_power2_scale" value="0.492063492" /></channel><channel id="phase3" type="output" ><scan-element index="6" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase3_label" value="BEAM0_H_EL3_DELAY" /><attribute name="raw" filename="out_phase3_raw" value="2" /><attribute name="scale" filename="out_phase3_scale" value="5.714285714" /></channel><channel id="power3" type="output" ><scan-element index="7" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power3_label" value="BEAM0_H_EL3_ATTENUATION" /><attribute name="raw" filename="out_power3_raw" value="0" /><attribute name="scale" filename="out_power3_scale" value="0.492063492" /></channel><channel id="phase4" type="output" ><scan-element index="8" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase4_label" value="BEAM0_V_EL0_DELAY" /><attribute name="raw" filename="out_phase4_raw" value="0" /><attribute name="scale" filename="out_phase4_scale" value="5.714285714" /></channel><channel id="power4" type="output" ><scan-element index="9" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power4_label" value="BEAM0_V_EL0_ATTENUATION" /><attribute name="raw" filename="out_power4_raw" value="0" /><attribute name="scale" filename="out_power4_scale" value="0.492063492" /></channel><channel id="phase5" type="output" ><scan-element index="10" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase5_label" value="BEAM0_V_EL1_DELAY" /><attribute name="raw" filename="out_phase5_raw" value="0" /><attribute name="scale" filename="out_phase5_scale" value="5.714285714" /></channel><channel id="power5" type="output" ><scan-element index="11" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power5_label" value="BEAM0_V_EL1_ATTENUATION" /><attribute name="raw" filename="out_power5_raw" value="0" /><attribute name="scale" filename="out_power5_scale" value="0.492063492" /></channel><channel id="phase6" type="output" ><scan-element index="12" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase6_label" value="BEAM0_V_EL2_DELAY" /><attribute name="raw" filename="out_phase6_raw" value="0" /><attribute name="scale" filename="out_phase6_scale" value="5.714285714" /></channel><channel id="power6" type="output" ><scan-element index="13" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power6_label" value="BEAM0_V_EL2_ATTENUATION" /><attribute name="raw" filename="out_power6_raw" value="0" /><attribute name="scale" filename="out_power6_scale" value="0.492063492" /></channel><channel id="phase7" type="output" ><scan-element index="14" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase7_label" value="BEAM0_V_EL3_DELAY" /><attribute name="raw" filename="out_phase7_raw" value="0" /><attribute name="scale" filename="out_phase7_scale" value="5.714285714" /></channel><channel id="power7" type="output" ><scan-element index="15" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power7_label" value="BEAM0_V_EL3_ATTENUATION" /><attribute name="raw" filename="out_power7_raw" value="0" /><attribute name="scale" filename="out_power7_scale" value="0.492063492" /></channel><channel id="phase8" type="output" ><scan-element index="16" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase8_label" value="BEAM1_V_EL0_DELAY" /><attribute name="raw" filename="out_phase8_raw" value="0" /><attribute name="scale" filename="out_phase8_scale" value="5.714285714" /></channel><channel id="power8" type="output" ><scan-element index="17" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power8_label" value="BEAM1_V_EL0_ATTENUATION" /><attribute name="raw" filename="out_power8_raw" value="0" /><attribute name="scale" filename="out_power8_scale" value="0.492063492" /></channel><channel id="phase9" type="output" ><scan-element index="18" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase9_label" value="BEAM1_V_EL1_DELAY" /><attribute name="raw" filename="out_phase9_raw" value="0" /><attribute name="scale" filename="out_phase9_scale" value="5.714285714" /></channel><channel id="power9" type="output" ><scan-element index="19" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power9_label" value="BEAM1_V_EL1_ATTENUATION" /><attribute name="raw" filename="out_power9_raw" value="0" /><attribute name="scale" filename="out_power9_scale" value="0.492063492" /></channel><channel id="phase10" type="output" ><scan-element index="20" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase10_label" value="BEAM1_V_EL2_DELAY" /><attribute name="raw" filename="out_phase10_raw" value="0" /><attribute name="scale" filename="out_phase10_scale" value="5.714285714" /></channel><channel id="power10" type="output" ><scan-element index="21" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power10_label" value="BEAM1_V_EL2_ATTENUATION" /><attribute name="raw" filename="out_power10_raw" value="0" /><attribute name="scale" filename="out_power10_scale" value="0.492063492" /></channel><channel id="phase11" type="output" ><scan-element index="22" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase11_label" value="BEAM1_V_EL3_DELAY" /><attribute name="raw" filename="out_phase11_raw" value="0" /><attribute name="scale" filename="out_phase11_scale" value="5.714285714" /></channel><channel id="power11" type="output" ><scan-element index="23" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power11_label" value="BEAM1_V_EL3_ATTENUATION" /><attribute name="raw" filename="out_power11_raw" value="0" /><attribute name="scale" filename="out_power11_scale" value="0.492063492" /></channel><channel id="phase12" type="output" ><scan-element index="24" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase12_label" value="BEAM1_H_EL0_DELAY" /><attribute name="raw" filename="out_phase12_raw" value="3" /><attribute name="scale" filename="out_phase12_scale" value="5.714285714" /></channel><channel id="power12" type="output" ><scan-element index="25" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power12_label" value="BEAM1_H_EL0_ATTENUATION" /><attribute name="raw" filename="out_power12_raw" value="0" /><attribute name="scale" filename="out_power12_scale" value="0.492063492" /></channel><channel id="phase13" type="output" ><scan-element index="26" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase13_label" value="BEAM1_H_EL1_DELAY" /><attribute name="raw" filename="out_phase13_raw" value="1" /><attribute name="scale" filename="out_phase13_scale" value="5.714285714" /></channel><channel id="power13" type="output" ><scan-element index="27" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power13_label" value="BEAM1_H_EL1_ATTENUATION" /><attribute name="raw" filename="out_power13_raw" value="0" /><attribute name="scale" filename="out_power13_scale" value="0.492063492" /></channel><channel id="phase14" type="output" ><scan-element index="28" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase14_label" value="BEAM1_H_EL2_DELAY" /><attribute name="raw" filename="out_phase14_raw" value="0" /><attribute name="scale" filename="out_phase14_scale" value="5.714285714" /></channel><channel id="power14" type="output" ><scan-element index="29" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power14_label" value="BEAM1_H_EL2_ATTENUATION" /><attribute name="raw" filename="out_power14_raw" value="0" /><attribute name="scale" filename="out_power14_scale" value="0.492063492" /></channel><channel id="phase15" type="output" ><scan-element index="30" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase15_label" value="BEAM1_H_EL3_DELAY" /><attribute name="raw" filename="out_phase15_raw" value="2" /><attribute name="scale" filename="out_phase15_scale" value="5.714285714" /></channel><channel id="power15" type="output" ><scan-element index="31" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power15_label" value="BEAM1_H_EL3_ATTENUATION" /><attribute name="raw" filename="out_power15_raw" value="0" /><attribute name="scale" filename="out_power15_scale" value="0.492063492" /></channel><channel id="temp16" type="input" ><scan-element index="32" format="le:U8/8&gt;&gt;0" scale="0.911500" /><attribute name="offset" filename="in_temp16_offset" value="86.362000" /><attribute name="raw" filename="in_temp16_raw" value="145" /><attribute name="scale" filename="in_temp16_scale" value="0.911500" /></channel><attribute name="amp_bias_mute_EL0V" value="0" /><attribute name="amp_bias_mute_EL1V" value="1" /><attribute name="amp_bias_mute_EL2V" value="0" /><attribute name="amp_bias_mute_EL3V" value="0" /><attribute name="amp_bias_operational_EL0H" value="3" /><attribute name="amp_bias_operational_EL0V" value="3" /><attribute name="amp_bias_operational_EL1H" value="3" /><attribute name="amp_bias_operational_EL1V" value="3" /><attribute name="amp_bias_operational_EL2H" value="3" /><attribute name="amp_bias_operational_EL2V" value="3" /><attribute name="amp_bias_operational_EL3H" value="3" /><attribute name="amp_bias_operational_EL3V" value="3" /><attribute name="amp_bias_reset_EL0V" value="3" /><attribute name="amp_bias_reset_EL1V" value="3" /><attribute name="amp_bias_reset_EL2V" value="3" /><attribute name="amp_bias_reset_EL3V" value="3" /><attribute name="amp_bias_sleep_EL0H" value="3" /><attribute name="amp_bias_sleep_EL0V" value="3" /><attribute name="amp_bias_sleep_EL1H" value="3" /><attribute name="amp_bias_sleep_EL1V" value="3" /><attribute name="amp_bias_sleep_EL2H" value="3" /><attribute name="amp_bias_sleep_EL2V" value="3" /><attribute name="amp_bias_sleep_EL3H" value="3" /><attribute name="amp_bias_sleep_EL3V" value="3" /><attribute name="amp_en_mute_EL0V" value="0" /><attribute name="amp_en_mute_EL1V" value="0" /><attribute name="amp_en_mute_EL2V" value="0" /><attribute name="amp_en_mute_EL3V" value="0" /><attribute name="amp_en_operational_EL0H" value="0" /><attribute name="amp_en_operational_EL0V" value="0" /><attribute name="amp_en_operational_EL1H" value="0" /><attribute name="amp_en_operational_EL1V" value="0" /><attribute name="amp_en_operational_EL2H" value="0" /><attribute name="amp_en_operational_EL2V" value="0" /><attribute name="amp_en_operational_EL3H" value="0" /><attribute name="amp_en_operational_EL3V" value="0" /><attribute name="amp_en_reset_EL0V" value="0" /><attribute name="amp_en_reset_EL1V" value="0" /><attribute name="amp_en_reset_EL2V" value="0" /><attribute name="amp_en_reset_EL3V" value="0" /><attribute name="amp_en_sleep_EL0H" value="0" /><attribute name="amp_en_sleep_EL0V" value="0" /><attribute name="amp_en_sleep_EL1H" value="0" /><attribute name="amp_en_sleep_EL1V" value="0" /><attribute name="amp_en_sleep_EL2H" value="0" /><attribute name="amp_en_sleep_EL2V" value="0" /><attribute name="amp_en_sleep_EL3H" value="0" /><attribute name="amp_en_sleep_EL3V" value="0" /><attribute name="beam0_fifo_rd" value="0" /><attribute name="beam0_fifo_wr" value="0" /><attribute name="beam0_load_mode" value="direct" /><attribute name="beam0_load_mode_available" value="direct memory fifo instant_direct reset mute" /><attribute name="beam0_mode" value="direct" /><attribute name="beam0_mode_available" value="direct memory fifo instant_direct reset mute" /><attribute name="beam0_ram_index" value="0" /><attribute name="beam0_ram_start" value="0" /><attribute name="beam0_ram_stop" value="63" /><attribute name="beam0_update" value="0" /><attribute name="beam1_fifo_rd" value="0" /><attribute name="beam1_fifo_wr" value="0" /><attribute name="beam1_load_mode" value="direct" /><attribute name="beam1_load_mode_available" value="direct memory fifo instant_direct reset mute" /><attribute name="beam1_mode" value="direct" /><attribute name="beam1_mode_available" value="direct memory fifo instant_direct reset mute" /><attribute name="beam1_ram_index" value="0" /><attribute name="beam1_ram_start" value="0" /><attribute name="beam1_ram_stop" value="63" /><attribute name="beam1_update" value="0" /><attribute name="beam2_fifo_rd" value="0" /><attribute name="beam2_fifo_wr" value="0" /><attribute name="beam2_load_mode" value="direct" /><attribute name="beam2_load_mode_available" value="direct memory fifo instant_direct reset mute" /><attribute name="beam2_mode" value="direct" /><attribute name="beam2_mode_available" value="direct memory fifo instant_direct reset mute" /><attribute name="beam2_ram_index" value="0" /><attribute name="beam2_ram_start" value="0" /><attribute name="beam2_ram_stop" value="63" /><attribute name="beam2_update" value="0" /><attribute name="beam3_fifo_rd" value="0" /><attribute name="beam3_fifo_wr" value="0" /><attribute name="beam3_load_mode" value="direct" /><attribute name="beam3_load_mode_available" value="direct memory fifo instant_direct reset mute" /><attribute name="beam3_mode" value="direct" /><attribute name="beam3_mode_available" value="direct memory fifo instant_direct reset mute" /><attribute name="beam3_ram_index" value="0" /><attribute name="beam3_ram_start" value="0" /><attribute name="beam3_ram_stop" value="63" /><attribute name="beam3_update" value="0" /><attribute name="update_intf_ctrl" value="pin" /><attribute name="update_intf_ctrl_available" value="pin SPI" /><buffer-attribute name="data_available" value="0" /><buffer-attribute name="watermark" value="1" /><debug-attribute name="direct_reg_access" value="0x18" /></device><device id="iio:device13" name="adar3002_csb_0_2" ><channel id="phase0" type="output" ><scan-element index="0" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase0_label" value="BEAM0_H_EL0_DELAY" /><attribute name="raw" filename="out_phase0_raw" value="2" /><attribute name="scale" filename="out_phase0_scale" value="5.714285714" /></channel><channel id="power0" type="output" ><scan-element index="1" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power0_label" value="BEAM0_H_EL0_ATTENUATION" /><attribute name="raw" filename="out_power0_raw" value="0" /><attribute name="scale" filename="out_power0_scale" value="0.492063492" /></channel><channel id="phase1" type="output" ><scan-element index="2" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase1_label" value="BEAM0_H_EL1_DELAY" /><attribute name="raw" filename="out_phase1_raw" value="1" /><attribute name="scale" filename="out_phase1_scale" value="5.714285714" /></channel><channel id="power1" type="output" ><scan-element index="3" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power1_label" value="BEAM0_H_EL1_ATTENUATION" /><attribute name="raw" filename="out_power1_raw" value="0" /><attribute name="scale" filename="out_power1_scale" value="0.492063492" /></channel><channel id="phase2" type="output" ><scan-element index="4" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase2_label" value="BEAM0_H_EL2_DELAY" /><attribute name="raw" filename="out_phase2_raw" value="2" /><attribute name="scale" filename="out_phase2_scale" value="5.714285714" /></channel><channel id="power2" type="output" ><scan-element index="5" format="le:u6/8&gt;&gt;0" scale="0.492063" /><attribute name="label" filename="out_power2_label" value="BEAM0_H_EL2_ATTENUATION" /><attribute name="raw" filename="out_power2_raw" value="0" /><attribute name="scale" filename="out_power2_scale" value="0.492063492" /></channel><channel id="phase3" type="output" ><scan-element index="6" format="le:u6/8&gt;&gt;0" scale="5.714286" /><attribute name="label" filename="out_phase3_label" value="BEAM0_H_EL3_DELAY" /><attribute name="raw" filename="out_phase3_raw" value="2" /><attribute name="scale" filename="out_phase3